Лабораторная работа №1
Выполнил студент группы БВТ2005 Камышев Владимир Владимирович

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [ ]:
import random
import time


In [6]:
import numpy as np
import random

user_min_limit = int(input())
user_max_limit = int(input())
user_m = int(input())
user_n = int(input())


matrix = np.random.randint(user_min_limit,user_max_limit,(user_m,user_n))
print(matrix)

0
200
200
200
[[ 93 178   7 ... 198 171 120]
 [ 91 151 186 ... 186 126  61]
 [ 82  24  78 ... 187  96   5]
 ...
 [ 88  20  90 ... 126 100 123]
 [186 129   0 ...  71  68  12]
 [177 148  24 ...  46  44 119]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [4]:
import copy

In [17]:
# Сортировка выбором

start_time = time.time()

import copy
import numpy as np
import time

def sort1(line):
    for i in range(len(line)):
        temp = line[i]
        index = i
        for j in range(i, len(line)):
            if line[j] < temp:
                temp = line[j]
                index = j
        line[index], line[i] = line[i], temp

array1 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array1:
    line = sort1(line)
t2 = time.time()

sort1_time = round((t2 - t1) * 1000)

print(matrix)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 198 198 199]
 [  0   1   1 ... 198 198 198]
 [  3   5   5 ... 198 198 199]
 ...
 [  0   0   2 ... 197 198 199]
 [  0   0   0 ... 194 197 198]
 [  1   2   2 ... 198 198 199]]
--- 753 ms ---


In [23]:
# Сортировка вставкой.

start_time = time.time()

import copy
import numpy as np
import time

def sort2(line):
    for i in range(1, len(line)):
        for j in range(i, 0, -1):
            if line[j] < line[j - 1]:
                line[j], line[j - 1] = line [j - 1], line[j]
            else:
                break
                
array2 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array2:
    line = sort2(line)
t2 = time.time()

sort2_time = round((t2 - t1) * 1000)

print(matrix)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 198 198 199]
 [  0   1   1 ... 198 198 198]
 [  3   5   5 ... 198 198 199]
 ...
 [  0   0   2 ... 197 198 199]
 [  0   0   0 ... 194 197 198]
 [  1   2   2 ... 198 198 199]]
--- 34 ms ---


In [35]:
# Сортировка обменом. || Сортировка пузырьком.

start_time = time.time()

import copy
import numpy as np
import time

def sort3(line):
    counter = 1
    while counter < len(line):
        for i in range(len(line) - counter):
            if line[i] > line[i + 1]:
                line[i], line[i + 1] = line[i + 1], line[i]
        counter += 1

array3 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array3:
    line = sort3(line)
t2 = time.time()

sort3_time = round((t2 - t1) * 1000)

print(matrix)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 198 198 199]
 [  0   1   1 ... 198 198 198]
 [  3   5   5 ... 198 198 199]
 ...
 [  0   0   2 ... 197 198 199]
 [  0   0   0 ... 194 197 198]
 [  1   2   2 ... 198 198 199]]
--- 1102 ms ---


In [43]:
# Сортировка Шелла.

start_time = time.time()

import copy
import numpy as np
import time
import math

def sort4(line):
    n = len(line)
    k = int(math.log2(n))
    interval = 2**k -1
    while interval > 0:
        for i in range(interval, n):
            temp = line[i]
            j = i
            while j >= interval and line[j - interval] > temp:
                line[j] = line[j - interval]
                j -= interval
            line[j] = temp
        k -= 1
        interval = 2**k -1
    return line

array4 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array4:
    line = sort4(line)
t2 = time.time()

sort4_time = round((t2 - t1) * 1000)

print(matrix)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 198 198 199]
 [  0   1   1 ... 198 198 198]
 [  3   5   5 ... 198 198 199]
 ...
 [  0   0   2 ... 197 198 199]
 [  0   0   0 ... 194 197 198]
 [  1   2   2 ... 198 198 199]]
--- 90 ms ---


In [41]:
# Быстрая сортировка.

start_time = time.time()

import copy
import numpy as np
import time

def sort5(line):
    if len(line) <= 1:
        return line
    temp = line[0]
    first_half = list(filter(lambda x : x < temp, line))
    middle = [i for i in line if i == temp]
    second_half = list(filter(lambda x : x > temp, line))
    return sort5(first_half) + middle + sort5(second_half)

array5 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array5:
    line = sort5(line)
t2 = time.time()

sort5_time = round((t2 - t1) * 1000)

print(matrix)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 198 198 199]
 [  0   1   1 ... 198 198 198]
 [  3   5   5 ... 198 198 199]
 ...
 [  0   0   2 ... 197 198 199]
 [  0   0   0 ... 194 197 198]
 [  1   2   2 ... 198 198 199]]
--- 960 ms ---


In [9]:
# Турнирная сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


### Вывод
