### Задание №1
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [11]:
import numpy as np

user_min = int(input())
user_max = int(input())
n = int(input())

A = np.random.randint(user_min, user_max, size=(n, 3)) 
max_num_index = np.argmax(A, axis=1)
 
max_per = 0 
max_array_index = 0 
 
print('Исходные данные:\n' + str(A))
 
for i in range(len(A)):
    if max_num_index[i] != 0:
        A[i,0], A[i, max_num_index[i]] = A[i, max_num_index[i]], A[i,0]
        
for i in range(len(A)):
    if (A[i,0]) < (A[i,1] + A[i,2]):
        if (A[i,0] + A[i,1] + A[i,2]) > max_per: 
            max_per, max_array_index = A[i,0] + A[i,1] + A[i,2], i
            
if max_per == 0:
    print('Такого треугольника не существует')
else:
    print('У треугольника со сторонами', A[max_array_index,0], A[max_array_index,1], A[max_array_index,2], 'максимальный периметр', max_per)


0
100
20
Исходные данные:
[[18 62 24]
 [94 76 78]
 [62 51 99]
 [90 60 24]
 [49 13 14]
 [63 87 71]
 [65 67 70]
 [ 5 44 19]
 [33 51 37]
 [ 1 60 42]
 [ 0 88 88]
 [98 79 80]
 [82 74 97]
 [28 71  1]
 [83  3 98]
 [99 86 35]
 [26 44 78]
 [ 7 82 19]
 [73 96 66]
 [85 16 48]]
У треугольника со сторонами 98 79 80 максимальный периметр 257


### Задание №2
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [3]:
import random

#Генерация массива 

min_limit = int(input())
max_limit = int(input())
m = int(input())

nums = np.random.randint(min_limit,max_limit,(m))

print('Исходный массив: \n' + str(nums))

nums = [str(i) for i in nums]

nums_to_fix = []

for i in nums:
    i = list(''.join(i))
    for j in i:
        nums_to_fix.append(j)

nums = sorted([int(i) for i in nums_to_fix],reverse = True)

string = ""

for i in nums:
    string += str(i)

print('Получившееся число: \n' + string)

0
100
50
Исходный массив: 
[51 77 41 29 28 43 27 88 99 83 63 53 14 11 81 36 83 59 70 62  5 98 50 59
 26  7 87 86 54 60 97 13 65  9 16 64  5 30 40 89 22 72 10  1 81 83 84 17
 68 47]
Получившееся число: 
99999999988888888888888777777777766666666665555555554444444433333333322222222111111111111000000


### Задание №3
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [7]:
import numpy as np
import random

#Генерация матрицы 

min_limit = int(input())
max_limit = int(input())
m = int(input())
n = int(input())

mat = np.random.randint(min_limit,max_limit,(m,n))
print('Исходная матрица: \n' + str(mat))



#Сортировка главной диагонали

for i in range(m):
    for j in range(i+1,n):
        if mat[i][i] > mat[j][j]:
            mat[i][i],mat[j][j] = mat[j][j],mat[i][i]

#Сортировка побочной диагонали

for i in range(m):
    for j in range(i+1,n):
        if mat[i][-i-1] < mat[j][-j-1]:
            mat[i][-i-1],mat[j][-j-1] = mat[j][-j-1],mat[i][-i-1]
            
print('Матрица с отсортированными диагоналями: \n' + str(mat))       
    

0
100
20
20
Исходная матрица: 
[[75 19 37 99 87 85 43 10 67  5 12 77 68 18 77 72 64 88  0 86]
 [16 80 75 43 64 74 26 62 18 80 81 11 46 16 73  8 17 91 37 66]
 [62 51 99 52 50 26 62 55 55 41 93 80 59 10 59 85 92  3 34 62]
 [62 98 94 87  2 86 48 83 51 54 51 43 41  0 31 73 37 86 19 55]
 [50 46 51 11 19 46 57 24 96 52  0 12 49 88 64 22  6 41 79  9]
 [ 8 36 99 99 26 52 96 66 29 24 96 83 33 83 63 91 46 58 76 69]
 [30 29 92 60 98  7 28 58 85 46  6 41  3 47 42  3 46 36 77 80]
 [10 65 54  3 22 92 99 35 80 79 26  9 16  8 74 81 65 65 35  8]
 [97 86  1 52 99 59 57 85 22 42 30 25 58 76 89 39 48 83 11 74]
 [26 53 22 84  6 52 37 84 94 54 73  0 86 69 38 87 63  4 22 20]
 [25 31 87 26 45 84 52 40 91  3 56 55 66 73  9 24 90 22 44 56]
 [21 92 31 28 99 22 31 14 29 43 75 75 59 40 48 60 78 65 22 98]
 [27 69 89 81 36 42 17 71 92  1 73 78  6 35  8 48 88  9  4 85]
 [44  5 38 46 46  2 93 55 10 86 10 53 27 39 43 87 23 78 23  1]
 [ 3 35 47 86 51 45  6 17 52 34 31 43 95 65  0 26  7 22 64 89]
 [44  9 19 80 12 50 47 9