Лабораторная работа №1
Выполнил студент группы БВТ2005 Камышев Владимир Владимирович

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [ ]:
import random
import time


In [58]:
import numpy as np
import random

user_min_limit = int(input())
user_max_limit = int(input())
user_m = int(input())
user_n = int(input())


matrix = np.random.randint(user_min_limit,user_max_limit,(user_m,user_n))
print(matrix)

0
200
200
200


TypeError: randint() takes 3 positional arguments but 4 were given

### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [4]:
import copy

In [14]:
# Сортировка выбором

start_time = time.time()

import copy
import numpy as np
import time


def sort1(line):
    for i in range(len(line)):
        temp = line[i]
        index = i
        for j in range(i, len(line)):
            if line[j] < temp:
                temp = line[j]
                index = j
        line[index], line[i] = line[i], temp

array1 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array1:
    line = sort1(line)
t2 = time.time()

sort1_time = round((t2 - t1) * 1000)

print(array1)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 443 ms ---


In [15]:
# Сортировка вставкой.

import copy
import numpy as np
import time

start_time = time.time()

def sort2(line):
    for i in range(1, len(line)):
        for j in range(i, 0, -1):
            if line[j] < line[j - 1]:
                line[j], line[j - 1] = line [j - 1], line[j]
            else:
                break
                
array2 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array2:
    line = sort2(line)
t2 = time.time()

sort2_time = round((t2 - t1) * 1000)

print(array2)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 1233 ms ---


In [16]:
# Сортировка обменом. || Сортировка пузырьком.

start_time = time.time()

import copy
import numpy as np
import time

def sort3(line):
    counter = 1
    while counter < len(line):
        for i in range(len(line) - counter):
            if line[i] > line[i + 1]:
                line[i], line[i + 1] = line[i + 1], line[i]
        counter += 1

array3 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array3:
    line = sort3(line)
t2 = time.time()

sort3_time = round((t2 - t1) * 1000)

print(array3)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 1563 ms ---


In [17]:
# Сортировка Шелла.

start_time = time.time()

import copy
import numpy as np
import time
import math

def sort4(line):
    n = len(line)
    k = int(math.log2(n))
    interval = 2**k -1
    while interval > 0:
        for i in range(interval, n):
            temp = line[i]
            j = i
            while j >= interval and line[j - interval] > temp:
                line[j] = line[j - interval]
                j -= interval
            line[j] = temp
        k -= 1
        interval = 2**k -1
    return line

array4 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array4:
    line = sort4(line)
t2 = time.time()

sort4_time = round((t2 - t1) * 1000)

print(array4)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 124 ms ---


In [88]:
# Быстрая сортировка.

start_time = time.time()

import copy
import numpy as np
import time

def sort5(line):
    if len(line) <= 1:
        return line
    else:
        temp = random.choice(line)
        first_half = []
        middle = []
        second_half = []
        for i in line:
            if i < temp:
                first_half.append(i) 
            elif i > temp: 
                second_half.append(i) 
            else: 
                middle.append(i)
        line = sort5(first_half) + middle + sort5(second_half)
        return line
        

array5 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array5:
    line = sort5(line)
t2 = time.time()

sort5_time = round((t2 - t1) * 1000)

print(array5)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 65 ms ---


In [89]:
# Турнирная сортировка.

import copy
import numpy as np
import time

start_time = time.time()

import heapq

from heapq import heappop, heappush  
   
def sort6(line):  
    heap = []  
    for ele in line:  
        heappush(heap, ele)  
    sort = []  
    while heap:  
        sort.append(heappop(heap))  
   
    return sort 

array6 = copy.deepcopy(matrix)                
t1 = time.time()                
for line in array6:
    line = sort6(line)
t2 = time.time()

sort6_time = round((t2 - t1) * 1000)

print(array6)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[  1   1   1 ... 193 193 196]
 [  0   4   7 ... 198 198 199]
 [  0   1   1 ... 198 199 199]
 ...
 [  1   1   4 ... 198 199 199]
 [  0   0   1 ... 197 198 199]
 [  0   1   3 ... 195 197 198]]
--- 18 ms ---


### Вывод


In [90]:
import copy
selection_sort = copy.deepcopy(sort1_time)
insertion_sort = copy.deepcopy(sort2_time)
bubble_sort = copy.deepcopy(sort3_time)
shell_sort = copy.deepcopy(sort4_time)
quick_sort = copy.deepcopy(sort5_time)
tournament_sort = copy.deepcopy(sort6_time)
array = ["Сортировка выбором - " + str(selection_sort) + " ms,", "Сортировка вставкой - " + str(insertion_sort) + " ms,", 
         "Сортировка пузырьком - " + str(bubble_sort) + " ms, ", "Сортировка Шелла - " + str(shell_sort) + " ms,", 
         "Быстрая сортировка - " + str(quick_sort) + " ms,", "Турнирная сортировка - " + str(tournament_sort) + " ms"]
print(*array)

Сортировка выбором - 443 ms, Сортировка вставкой - 1233 ms, Сортировка пузырьком - 1562 ms,  Сортировка Шелла - 122 ms, Быстрая сортировка - 63 ms, Турнирная сортировка - 17 ms
