# Лабораторная работа №3
## Выполнил студент группы БВТ2005 Камышев Владимир

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
4. [Вывод](#Вывод)

> Дополнительные модули, использованные при выполнение лабораторной

In [1]:
# Необходим при замере скорости выполнения кода
from datetime import datetime as t
# Нужен для создания словаря в алг. Бойера-Мура
from collections import defaultdict

### Задание №1
Реализовать методы поиска подстроки в строке. Добавить возможность ввода строки и подстроки с клавиатуры. Предусмотреть возможность существования пробела. Реализовать возможность выбора опции чувствительности или нечувствительности к регистру. Оценить время работы каждого алгоритма поиска и сравнить его со временем работы стандартной функции поиска, используемой в выбранном языке программирования.

#### Алгоритм Кнута-Морриса-Пратта

In [18]:
def prefix_function(string):
    n = len(string)
    pi = [0] * n
    for i in range(1,n):
        j = pi[i-1]
        while j > 0 and string[j] != string[i]:
            j = pi[j-1]
        if string[i] == string[j]:
            j += 1
        pi[i] = j
    return pi

def kmp_search(string, substring, start_index = 0):
    j = 0
    pi = prefix_function(substring)
    for i in range(start_index, len(string)):
        while j > 0 and string[i] != substring[j]:
            j = pi[j-1]
        if string[i] == substring[j]:
            j += 1
        if j >= len(substring):
            return i - j + 1
    return None
    
string = "eeertrtrtrtrrtrtrtr"
substring = "trrt"

print(kmp_search(string,substring,0))

10


#### Упрощенный алгоритм Бойера-Мура

In [23]:
def bm_search(string, substring):
    m = len(substring)
    n = len(string)
    i = m - 1 
    j = m - 1  
    while i < n:
        if string[i] == substring[j]:
            if j == 0:
                return i
            else:
                i -= 1
                j -= 1
        else:
            i = i + m - min(j, 1+i)
            j = m - 1 
    return -1

string = "eeertrtrtrtrrtrtrtr"
substring = "trrt"
print(bm_search(string,substring))

10


### Задание №2
Написать программу, определяющую, является ли данное
расположение «решаемым», то есть можно ли из него за конечное число
шагов перейти к правильному. Если это возможно, то необходимо найти хотя
бы одно решение - последовательность движений, после которой числа будут
расположены в правильном порядке.
#### Входные данные: массив чисел, представляющий собой расстановку в
Порядке «слева направо, сверху вниз». Число 0 обозначает пустое поле.
Например, массив [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0] представляет
собой «решенную» позицию элементов.
#### Выходные данные: если решения нет, то функция должна вернуть
Пустой массив []. Если решение есть, то необходимо представить решение —
для каждого шага записывается номер передвигаемого на данном шаге
элемента. 

In [122]:
import numpy as np

array = np.array([2,6,13,7,8,10,15,1,0,3,4,5,9,11,12,14])

array = array.reshape(4,4)

print(str(array) + '\n')

def sort_by_columns(array):
    lst = sorted(itertools.chain.from_iterable(array))
    return [lst[i::len(array)] for i in range(len(array))]
    

array = np.array(sort_by_columns(array))

print(str(array) + '\n')

array = np.transpose(array)

print(str(array) + '\n')

array = np.delete(array, 0)
array = np.append(array, 0)
print(array.reshape(4,4))


[[ 2  6 13  7]
 [ 8 10 15  1]
 [ 0  3  4  5]
 [ 9 11 12 14]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


### Вывод